# Nome da Aplicação
spring.application.name=AuditSystem

# Configuração do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_system
spring.datasource.username=user_audit
spring.datasource.password=password_audit
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate (JPA)
# update: cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# URL do seu serviço Python (FastAPI)
python.service.url=http://127.0.0.1:8000